# -*- eval: (save-excursion (org-babel-goto-named-src-block "workshopPreamble") (org-babel-execute-src-block)) -*-
#+TITLE:     Installation von Ansible
#+AUTHOR:    Jörg Reuter
#+EMAIL:     joerg@reuter.sc
#+DATE:      

#+PROPERTY: exports both
#+EXCLUDE_TAGS: noexport mitsetup
#+SETUPFILE: ../workshopPreamble.org

#+name: workshopPreamble
#+begin_src emacs-lisp :exports none :results silent :tangle no
  (load-file "../setupEnvironment.el")
#+end_src

* Installation

Das Programm Ansible ist in Python programmiert. Daher müssen wir Python auch installieren.

#+name: python_install
#+begin_src bash
apt update
apt -y install git python python-dev python-pip openssl python-software-properties software-properties-common
sudo apt-add-repository ppa:ansible/ansible
apt update
apt -y install git python python-dev python-pip openssl ansible
apt -y dist-upgrade
#+end_src

Mit dem folgenden  Befehl überprüfen wir die Installation:

#+name: ansible_version
#+begin_src bash
ansible --version
#+end_src

Als Ausgabe sollte erscheinen (oder höhere Version): 

#+name: ansible_version_ausgabe
#+begin_src bash
ansible 2.0.0.2
#+end_src

Die Version ist leider nicht mehr ganz aktuell. Daher installieren wir den Server von einer anderen Quelle:

#+name: ansible_ppa
#+begin_src bash
sudo apt-add-repository ppa:ansible/ansible
apt update
apt dist-upgrade
#+end_src

Jetzt sollte der Befehl

#+name: ansible_ansible_neu
#+begin_src bash 
ansible --version
#+end_src

die Version 2.3.0.0 oder höher ausgeben. Darunter erscheint der Pfad zur Konfigurationsdatei. Diese öffnen wir mit einem Texteditor:


#+name: ansible_ansible_cfg
#+begin_src bash 
vim /etc/ansible/ansible.cfg
#+end_src

In der Datei entfernen wir das Kommentarzeichen vor zwei Zeilen:

#+name: ansible_ansible_aenderung
#+begin_src bash
inventory      = /etc/ansible/hosts
sudo_user      = root
#+end_src

Beide Zeilen sind im [defaults]-Bereich. Danach speichern wir die Datei ab.

Ansible hat keinen Hintergrundprozess und braucht daher nicht neu gestartet zu werden.

Wir wechseln in den Ordner /etc/ansible (den Pfad hatten wir eben in der Konfigurationsdatei aktiviert) und sichern dort die hosts-Datei:

#+name: ansible_ansible_mv
#+begin_src bash 
mv hosts host.backup
#+end_src

Wir öffnen die Datei hosts (eine leere Datei) und tragen folgendes ein:


#+name: ansible_host
#+begin_src bash
[local]
localhost

[ubuntu]
Ubuntu.node

[centos]
Centos.node
#+end_src

Für beide Server tragen wir die IP-Adresse in die Datei /etc/hosts ein.

Wir führen möglichst alle Programme und Server mit Benutzern aus, die möglichst wenig Rechte auf dem Server haben. Daher legen wir einen neuen Benutzer an:


#+name: ansible_adduser
#+begin_src bash 
adduser ansible
#+end_src

Wir müssen den Benutzer ansible jetzt noch in die Gruppe der sudoers einfügen. Dies ermöglicht ansible privilegierte Befehle zu starten. Wir müssen darauf achten, dass ansible dafür kein Passwort braucht:

Mit dem Befehl 

#+name: visudo
#+begin_src bash 
visudo
#+end_src

öffnen wir die Konfiguratiosdatei um ansible temporären Systemzugriff zu gewähren und fügen unterhalb der Zeile 


#+name: user_konfig
#+begin_src bash 
root    ALL=(ALL:ALL) ALL
ansible ALL=(ALL) NOPASSWD: ALL
#+end_src

ein.

Das Anlegen des Benutzers und die Vergabe des Passworts müssen wir auf jedem System durchführen.

Um das Problemlose verwalten der Nodes zu ermöglichen, richten wir für ssh eine Key-basierte Anmeldung ein:

#+name: ssh-keygen
#+begin_src bash
su ansible -
ssh-keygen
#+end_src

Als nächstes kopieren wir die Schlüssel auf die Server:

#+name: ssh-copy
#+begin_src bash
ssh-copy-id ansible@Ubuntu.node
#+end_src

** Achtung vServer mit KeyAuth

Damit der Befehl ssh-copy-id z.B. bei DigitalOcean funktioniert, muss folgendes Workaround eingesetzt verwendet werden:

In der Datei  /etc/ssh/sshd_config muss die Zeile PasswordAuthentication no zu PasswordAuthentication yes verändert werden. Anschließend ist der Dienst mit 

#+name: sshd_config
#+begin_src bash
sudo systemctl restart sshd 
#+end_src

neu zu starten.

** SSH-Key lokal kopieren

Mit dem Befehl

#+name: ssh
#+begin_src bash
ssh 'ansible@54.154.150.210'
#+end_src

testen wir die Erfolgreiche Einrichtung. Es sollte jetzt möglich sein, ohne Passwort auf den anderen Computer zugriff zu erhalten.

Damit die Clients auf den Server zugreifen können, müssen wir die ssh-id auch auf unseren Server installieren:

#+name: ssh-copy-local
#+begin_src bash
ssh-copy-id ansible@localhost
#+end_src

-----------------------------------------------------
* Testumgebung

Wir gehen von 3 Servern zu testzwecken aus mit jeweils Ubuntu 16.04 installiert.

Wir möchten Ansible aus Sicherheitsgründen nicht unter root laufen lassen. Wir legen daher auf jeder Maschine einen User (Name beliebig) und in seinem Home-Verzeichnis den Ordner playbooks an und setzen die Berechtigungen noch richtig.:

adduser ansible
cd /home/ansible
mkdir playbooks
chown ansible:ansible playbooks/

Wir gehen in das Verzeichnis /etc/ansible und schauen uns den Inhalt an:

cd /etc/ansible
ll

** Hosts-Datei

Wir verschieben die Hosts-Datei und legen eine neue an:

mv hosts hosts.orig

vim hosts

[local]
localhost

[apachehosts]
47.90.200.64

[gitserver]
47.90.204.43

Wir können uns alkle konfigurierten Systeme anzeigen lassen:

ansible all --list-host

Wir konfigurieren das Key-Auth für ssh:

Wir speichern die Datei fbs.pem in den /root/.ssh-Ordner und passen die .ssh/config-Datei an (wenn nicht vorhanden, einfach anlegen):

Hostname 47.90.204.43
Hostname 47.90.200.64
IdentityFile2 ./fbs.pem
Port 22
PreferredAuthentications publickey
Protocol 2
User root

Wir können jetzt alle Maschinen anpingen:

ansible all -m ping

Oder bestimmte Gruppen:

ansible gitserver -m ping

Solange die Ausgabe grün bleibt, ist alles ok.

root@iZ0xie4k1y0gs0kk3lphsjZ:~/.ssh# ansible gitserver -m ping
47.90.204.43 | SUCCESS => {
    "changed": false,
    "failed": false,
    "ping": "pong"
}

Wir können eine bestimmte host-Datei mitgeben durch den Parameter -i:

ansible 47.90.200.64 -i /home/user/hosts -m ping

Auch die ansible.cfg kann überschrieben werden: ansible überprüft automatisch das Verzeichnis indem ansible gestartet wird nach einer Datei mit dem Namen ansible.cfg und führte diese dann aus.

* Ansible auf der Konsole

Wir möchten wissen, welche python-Module auf den Servern der Gruppe 'gitserver' installiert sind. Das Anzeigend er aktuell installierten Pakete geschieht durch den Befehl

dpkg-query -l|grep python

Mit dem Befehl

ansible gitserver -m shell -a 'dpkg-query -l|grep python'

Der Befehl bedeutet, dass auf den Servern der Gruppe gitserver die Shell geöffnet wird und wir in der Shell den Befehl ausführen.

Wir können statt der Gruppe auch die IP oder den NAmen einzelner Server aus der hosts-Datei angeben.

* Aufgabe 

Schreibe einen Befehl, der auf den Servern der Gruppe 'webservers' mariadb-server und mariadb-client installiert. Der Befehl für die Konsole lautet: 

apt -y install mariadb-client mariadb-server

Um wichtige Systemdaten abzufragen, gibt es den Befehl setup:

ansible local -m setup|more

Wir können die Ausgaben auch in eine Datei kopieren:

ansible localhost -m setup --tree /tmp/info



