# -*- eval: (save-excursion (org-babel-goto-named-src-block "workshopPreamble") (org-babel-execute-src-block)) -*-
#+TITLE:     Installation von Ansible
#+AUTHOR:    Jörg Reuter
#+EMAIL:     joerg@reuter.sc
#+DATE:      

#+PROPERTY: exports both
#+EXCLUDE_TAGS: noexport mitsetup
#+SETUPFILE: ../workshopPreamble.org

#+name: workshopPreamble
#+begin_src emacs-lisp :exports none :results silent :tangle no
  (load-file "../setupEnvironment.el")
#+end_src

* Installation

Das Programm Ansible ist in Python programmiert. Daher müssen wir Python auch installieren.

#+name: python_install
#+begin_src bash
apt update
apt -y install git python python-dev python-pip software-properties-common openssl
apt-add-repository ppa:ansible/ansible
apt update
apt -y install ansible
apt -y dist-upgrade
#+end_src

Mit dem folgenden  Befehl überprüfen wir die Installation:

#+name: ansible_version
#+begin_src bash
ansible --version
#+end_src

Der Befehl sollte eine Version von 2.4.0.0 oder höher ausgeben. Darunter erscheint der Pfad zur Konfigurationsdatei. Diese öffnen wir mit einem Texteditor:


#+name: ansible_ansible_cfg
#+begin_src bash 
vim /etc/ansible/ansible.cfg
#+end_src

Ansible hat keinen Hintergrundprozess und braucht daher nicht neu gestartet zu werden.

Wir wechseln in den Ordner /etc/ansible (den Pfad hatten wir eben in der Konfigurationsdatei aktiviert) und sichern dort die hosts-Datei:

#+name: ansible_ansible_mv
#+begin_src bash 
mv hosts host.backup
#+end_src

* Testumgebung

Wir gehen von 3 Servern zu Testzwecken aus, mit jeweils Ubuntu 16.04 installiert.

Wir gehen in das Verzeichnis /etc/ansible und schauen uns den Inhalt an:

#+begin_src
cd /etc/ansible
ll
#+end_src

** Hosts-Datei

Wir verschieben die Hosts-Datei und legen eine neue an:

#+begin_src
mv hosts hosts.orig
vim hosts
#+end_src

#+begin_src
[local]
localhost

[apachehosts]
47.90.200.64

[gitserver]
47.90.204.43
#+end_src

Wir können uns aktuell konfigurierten Systeme anzeigen lassen:

#+begin_src
ansible all --list-host
#+end_src

** Key-Auth

Wir konfigurieren das Key-Auth für ssh:

Wir speichern die Datei fbs.pem in den /root/.ssh-Ordner und passen die .ssh/config-Datei an (wenn nicht vorhanden, einfach anlegen):

#+begin_src
Host *
IdentityFile2 ./fbs.pem
Port 22
PreferredAuthentications publickey
Protocol 2
User root
#+end_src

Wir können jetzt alle Maschinen anpingen:

#+begin_src
ansible all -m ping
#+end_src

Oder bestimmte Gruppen:

#+begin_src
ansible gitserver -m ping
#+end_src

Solange die Ausgabe grün bleibt, ist alles ok.

#+begin_src
root@iZ0xie4k1y0gs0kk3lphsjZ:~/.ssh# ansible gitserver -m ping
47.90.204.43 | SUCCESS => {
    "changed": false,
    "failed": false,
    "ping": "pong"
}
#+end_src

Wir können eine bestimmte host-Datei mitgeben durch den Parameter -i:

#+begin_src
ansible 47.90.200.64 -i /home/user/hosts -m ping
#+end_src

Auch die ansible.cfg kann überschrieben werden: ansible überprüft automatisch das Verzeichnis indem ansible gestartet wird nach einer Datei mit dem Namen ansible.cfg und führte diese dann aus.

* Ansible auf der Konsole

Wir möchten wissen, welche python-Module auf den Servern der Gruppe 'gitserver' installiert sind. Das Anzeigend er aktuell installierten Pakete geschieht durch den Befehl

#+begin_src
dpkg-query -l|grep python
#+end_src

Mit dem Befehl

#+begin_src
ansible gitserver -m shell -a 'dpkg-query -l|grep python'
#+end_src

Der Befehl bedeutet, dass auf den Servern der Gruppe gitserver die Shell geöffnet wird und wir in der Shell den Befehl ausführen.

Wir können statt der Gruppe auch die IP oder den NAmen einzelner Server aus der hosts-Datei angeben.

* Aufgabe 

Schreibe einen Befehl, der auf den Servern der Gruppe 'webservers' mariadb-server und mariadb-client installiert. Der Befehl für die Konsole lautet: 

#+begin_src
apt -y install mariadb-client mariadb-server
#+end_src

Um wichtige Systemdaten abzufragen, gibt es den Befehl setup:


#+begin_src
ansible local -m setup|more
#+end_src


Wir können die Ausgaben auch in eine Datei kopieren:


#+begin_src
ansible localhost -m setup --tree /tmp/info
#+end_src

Um den Baum zu durchsuchen nach einem bestimmten Eintrag wie z.B. die IPv4-Adressen, könnten wir grep verwednen:

#+begin_src
ansible localhost -m setup --tree /tmp/info|grep ipv4
#+end_src

Das gibt aber nur die Zeile aus und nicht die gesuchten Informationen (die stehen ja in der geschweiften Klammer):

#+begin_src
root@iZ0xie4k1y0gs0kk3lphsjZ:~# ansible gitserver -m setup |grep ipv4
        "ansible_all_ipv4_addresses": [
        "ansible_default_ipv4": {
                "tx_checksum_ipv4": "off [fixed]",
            "ipv4": {
                "tx_checksum_ipv4": "off [fixed]",
            "ipv4": {
#+end_src

Deshalb verwednen wir den Filter-Befehl, der die Klammern mit ausgibt:

#+begin_src
root@iZ0xie4k1y0gs0kk3lphsjZ:~# ansible gitserver -m setup -a 'filter=*ipv4*'
47.90.204.43 | SUCCESS => {
    "ansible_facts": {
        "ansible_all_ipv4_addresses": [
            "172.22.59.240"
        ],
        "ansible_default_ipv4": {
            "address": "172.22.59.240",
            "alias": "eth0",
            "broadcast": "172.22.63.255",
            "gateway": "172.22.63.253",
            "interface": "eth0",
            "macaddress": "00:16:3e:00:28:91",
            "mtu": 1500,
            "netmask": "255.255.240.0",
            "network": "172.22.48.0",
            "type": "ether"
        }
    },
    "changed": false,
    "failed": false
}
#+end_src

** Aufgabe

1.) Schreibe einen Befehl, der den verbauten Prozessor zurück gibt.
2.) Probiere folgende Befehle aus:

#+begin_src
ansible gitserver -m setup -a 'filter=ansible_architecture'
ansible gitserver -m setup -a 'filter=ansible_distribution'
ansible gitserver -m setup -a 'filter=ansible_distribution_version'
ansible gitserver -m setup -a 'filter=ansible_domain'
ansible gitserver -m setup -a 'filter=ansible_fqdn'
ansible gitserver -m setup -a 'filter=ansible_kernel'
ansible gitserver -m setup -a 'filter=ansible_memtotal_mb'
#+end_src

* Playbook

Für das Playbook müssen wir die Befehle besser aufabuen und flexibler gestalten. Wir installieren den browser lynx in einer Gruppe:

#+begin_src
ansible gitserver -m apt -a 'name=lynx  state=installed update_cache=true'
#+end_src

Wir sagen, wir verwenden die Vorlage (Modell) apt und sagen, das PAket soll den Status installed haben und die Metadaten der Pakete sollen aktuell sein. Wenn lynx nicht installiert ist, wird dies nachgeholt. Wenn es installiert ist, wird nichts gemacht.

Wir legen ein verzeichnis an mit der Bezeichnung playbooks:

#+begin_src
mkdir playbooks
cd playbooks
#+end_src

Wir legen ein File mit dem namen gitserver.yml an ,it folgendem Inhalt:

#+begin_src
- hosts: gitserver
  tasks:
  - name: Install Lynx in der Gruppe gitserver
    apt: name=lynx  state=installed update_cache=true
#+end_src

und führen die Datei aus:

#+begin_src
ansible-playbook gitserver.yml
#+end_src

* Variable

Variablen im Playbook. Variablen werden immer am Anfang definiert.

#+begin_src
- hosts: gitserver
  vars:
    control_server: 47.90.204.43
    web_root: /var/www/html
  tasks:
  - name: Install Lynx in der Gruppe gitserver
    apt: name=lynx  state=installed update_cache=true
#+end_src

* Include von Yaml-Dateien:


#+begin_src
- hosts: gitserver
  vars_files:
  - vars.yml
  vars:
    control_server: 47.90.204.43
    web_root: /var/www/html
  tasks:
  - name: Install Lynx in der Gruppe gitserver
    apt: name=lynx  state=installed update_cache=true

#+end_src









