* Einführung
Die Einführung in das Thema Datenbanken ist schwierig. Das liegt daran, dass bei Datenbanken sehr viele Dinge ineinander greifen:

- Datenbank-Server (MySQL, MariDB, Oracle, SQL-Server (Microsoft) etc.) 
- Server-Betriebssystem (Windows Server, Linux etc.)
- Client für Datenbankabfragen (mysql-client, phpmyadmin, mySQL-Workbench etc.)
- Abfragesprachen (z.B. SQL in diversen Dialekten)
- Aufbau von Datenbank (Normalformen etc.)
- Vielfältige Anwendungen von Datenbanken mit entsprechender Programmiersprache (PHP, Pearl, Python etc.)
- Sicherheit von Datenbanken (Backup nicht unproblematisch, Clusterbetrieb nicht einfach, Häufig Ziel von Angriffen)
- Netzwerktechnik da Datenbanken meist über Netzwerke erreichbar sind.

Datenbanken sind also kurz gesagt ein Kristallationspunkt der gesamten IT. Ohne Datenbanken sind die meisten Anwendung in der IT nicht denkbar. Sie sind einer der Teile, die in einer Infrastruktur in allen belangen kritisch sind. Sie stellen zzum Teil sehr hohe Anforderungen an die Hardware, gerade weil Datenbanken extrem zeitkritisch sind und gerade in virtualisierten Umgebungen problematisch werden. Datenbanken sind Sicherheitskritisch weil sie auf der einen Seite kritische Daten vorhalten und auf der anderen Seite in einem Unternehmen oft einen Single Point of Failure darstellen. Zu allem überfluss bedingen die beiden vorher genannten Punkte auch noch, dass Backup und Clusterbetrieb von Datenbanken nicht trivial ist aber Aufgrund Ihrer Bedeutung im Unternehmen dringend zu empfehlen ist. Es gibt dann noch eine nicht zu überschauende Anzahl von Anwendungen, die Datenbanken verwenden und jede hat ihre spezielle Anforderung an die Systeme und unterschiedliche Zugriffsweisen. Auch die Entwicklung in der IT ist im Bereich Datenbanken sehr stark (Big Data, NoSQL-Datenbanken etc.). Datenbanken ist also ein Thema, dass völlig zurecht erst im 3. Lehrjahr ernsthaft verstanden werden kann.

Um den Einstieg zu erleichtern, werden wir mit einem Film anfangen, der ev. von der Thematik etwas überraschend ist: Schatzsuche im Genlabor (http://www.zdf.de/ZDFmediathek/beitrag/video/1750526/Schatzsuche-im-Genlabor#/beitrag/video/1750526/Schatzsuche-im-Genlabor). Die DNA ist eine riesige Datenbank von Informationen und der Aufbau der DNA verschiedener Lebewesen wie dem menschen oder aber auch der Maus werden in Datenbanken erfasst. Das bedeutet, dass wir hier an einer Stelle sind, ander eine biologische Datenbank in eine Datenbank in einem IT-System überführt wird. Und wir sind hier an einem Brennpunkt der Forschung für die nächsten Jahrzehnte. Auch aktuelle Entwicklungen wie BigData sind hier wunderbar abzulesen.

** Genug der langen Worte
Wir werden uns die zuerst nur um den Teilbereich "Abruf von Informationen aus Datenbanken" kümmern, wie wir auf eine Datenbank zugreifen. Welche Unterschiedliche Wege es dafür gibt und nebenbe




* Dr. Codds 12 Regeln
We owe to Dr. Edgar F. Codd the concept of the relational model, from his 1970
paper A Relational Model of Data for Large Shared Data Banks ( http://www.acm.
org/classics/nov95/toc.html ). Dr. Codd later explained his model by defining
a set of rules – the so-called Codd's Twelve rules ( http://en.wikipedia.org/
wiki/Codd%27s_12_rules ). An ideal database management system (DBMS) would
implement all those rules, but few if any do.

* Beispiel
Wir erstellen die Datenbank für ein Computergeschäft. Das Geschäft heißt "Fredy Braun Software" oder Abgekürzt FBS. Wir fangen an mit dem erfassen der Verkauften Hardware.

Wir bekommen folgende Tabelle zur Verfügung gestellt:
| Verkäufer     | Zeitraum       | Hersteller | Typ-Nummer | Bezeichnung und Jahr | Anzahl |
|---------------+----------------+------------+------------+----------------------+--------|
| Müller, Erwin | August 2016    | DELL       |            |                      |      3 |
| Müller, Erwin | August 2016    | IBM        |            |                      |      7 |
| Müller, Erwin | September 2016 | HP         |            |                      |      4 |
| Baier, Klaus  | August 2016    | HP         |            |                      |      1 |
| Baier, Klaus  | August 2016    | DELL       |            |                      |      1 |
| Baier, Klaus  | September 2016 | SGI        |            |                      |      6 |

Die Tabelle müssen wir zur Verwendung in einer Datenbank etwas umformatieren:
| verkaeufer | hersteller | typ_nummer | bezeichnung_jahr | qtj_2016_08 | qtj_2016_09 |
|------------+------------+------------+------------------+-------------+-------------|
|            |            |            |                  |             |             |


Um die Tabelle anlegen zu können müssen wir zerst eine Datenbank anlegen. Dies können wir entweder über die Weboberfläche phpMyAdmin machen oder aber über die Kommandozeile mit dem Befehl mysql -u root -pfbs. 

Der Befehl dazu lautet:
#+BEGIN_SRC SQL
create database fbs;
#+END_SRC

Dann müssen wir die Datenbank zur Benutzung auswählen. Dies geschieht mit:
#+BEGIN_SRC SQL
use fbs;
#+END_SRC

und das Anlegen der Tabelle dann mit dem Befehl:
#+BEGIN_SRC SQL
CREATE TABLE verkauf (
verkaeufer char(40) NOT NULL,
hersteller char(40) NOT NULL,
typ_nummer char(40) NOT NULL,
bezeichnung_jahr char(40) NOT NULL,
qtj_2016_08 int(11) NOT NULL,
qtj_2016_09 int(11) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
#+END_SRC
geht auch utf statt latin1?

Nachdem wir die Tabelle angelegt haben, tragen wir  die Werte von der Tabelle oben ein:
#+BEGIN_SRC SQL
INSERT INTO sales VALUES ('Müller, Erwin', 'DELL', '1A8','Mitsou 2007', 3 |
| Müller, Erwin | August 2016    | IBM        |            |                      |      7 |
| Müller, Erwin | September 2016 | HP         |            |                      |      4 |
| Baier, Klaus  | August 2016    | HP         |            |                      |      1 |
| Baier, Klaus  | August 2016    | DELL       |            |                      |      1 |
| Baier, Klaus  | September 2016 | SGI        |            |                      |      6 |

Die Tabelle müssen wir zur Verwendung in einer Datenbank etwas umformatieren:
| verkaeufer | hersteller | typ_nummer | bezeichnung_jahr | qtj_2016_08 | qtj_2016_09 |
|------------+------------+------------+------------------+-------------+-------------|
|            |            |            |                  |             |             |


Um die Tabelle anlegen zu können müssen wir zerst eine Datenbank anlegen. Dies können wir entweder über die Weboberfläche phpMyAdmin machen oder aber über die Kommandozeile mit dem Befehl mysql -u root -pfbs. 

Der Befehl dazu lautet:
#+BEGIN_SRC SQL
create database fbs;
#+END_SRC

Dann müssen wir die Datenbank zur Benutzung auswählen. Dies geschieht mit:
#+BEGIN_SRC SQL
use fbs;
#+END_SRC

und das Anlegen der Tabelle dann mit dem Befehl:
#+BEGIN_SRC SQL
CREATE TABLE verkauf (
verkaeufer char(40) NOT NULL,
hersteller char(40) NOT NULL,
typ_nummer char(40) NOT NULL,
bezeichnung_jahr char(40) NOT NULL,
qtj_2016_08 int(11) NOT NULL,
qtj_2016_09 int(11) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
#+END_SRC
geht auch utf statt latin1?

Nachdem wir die Tabelle angelegt haben, tragen wir  die Werte von der Tabelle oben ein:

| Verkäufer     | Zeitraum       | Hersteller | Typ         | Bezeichnung und Jahr | Anzahl |
|---------------+----------------+------------+-------------+----------------------+--------|
| Müller, Erwin | August 2016    | HP         | Workstation | Z840 2016            |      7 |
| Müller, Erwin | August 2016    | DELL       | Workstation | Precision 7910 2015  |      8 |
| Müller, Erwin | September 2016 | DELL       | Workstation | Precision 7910 2015  |      1 |
| Müller, Erwin | September 2016 | HP         | Server      | Z840 2016            |      4 |
| Baier, Klaus  | August 2016    | HP         | Server      | Apollo 6500    2016  |      1 |
| Baier, Klaus  | August 2016    | DELL       | Workstation | Precison 7910  2016  |      1 |
| Baier, Klaus  | September 2016 | IBM        | Server      | Power E880     2016  |      6 |
| Baier, Klaus  | September 2016 | HP         | Server      | Apollo 6500          |      2 |

Die Tabelle müssen wir zur Verwendung in einer Datenbank etwas umformatieren:

| verkaeufer    | hersteller | typx        | bezeichnung_jahr | qtj_2016_08 | qtj_2016_09 |
|---------------+------------+-------------+------------------+-------------+-------------|
| Müller, Erwin | HP         | Workstation | Z840 2016        |           7 |           4 |
| Müller, Erwin | DELL       | Workstation | Precison 7910    |           8 |           1 |
| Baier, Klaus  | HP         | Server      | Apollo 6500      |           1 |           2 |
| Baier, Klaus  | DELL       | Workstation | Precision 7910   |           1 |           1 |
| Baier, Klaus  | IBM        | Server      | Power E880       |           0 |           6 |
|                                                                                         |

** Aufgabe:  
Bitte fülle die Tabelle vollständig aus.
 
Um die Tabelle anlegen zu können müssen wir zerst eine Datenbank anlegen. Dies können wir entweder über die Weboberfläche phpMyAdmin machen oder aber über die Kommandozeile mit dem Befehl mysql -u root -pfbs. 

Der Befehl dazu lautet:
#+BEGIN_SRC SQL
create database fbs;
#+END_SRC

Dann müssen wir die Datenbank zur Benutzung auswählen. Dies geschieht mit:
#+BEGIN_SRC SQL
use fbs;
#+END_SRC

und das Anlegen der Tabelle dann mit dem Befehl:
#+BEGIN_SRC SQL
CREATE TABLE verkauf (
verkaeufer char(40) NOT NULL,
hersteller char(40) NOT NULL,
typ_nummer char(40) NOT NULL,
bezeichnung_jahr char(40) NOT NULL,
qtj_2016_08 int(11) NOT NULL,
qtj_2016_09 int(11) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
#+END_SRC
* TODO
geht auch utf statt latin1?

Nachdem wir die Tabelle angelegt haben, tragen wir  die Werte von der Tabelle oben ein:

#+BEGIN_SRC SQL
INSERT INTO sales VALUES ('Müller, Erwin', 'HP', '1A8','Mitsou 2007',7 , 4);
#+END_SRC 

** Aufgabe:
Bitte trage die restlichen Zeilen, aus der Tabelle oben, ebenfalls in die Tabelle ein.

** Probleme der Struktur
In welcher Spalte speichern wir die Werte vom Oktober und November ab?

Die anderen Probleme ergeben sich, wenn wir ein wenig mit der Tabelle herum spielen.

* Max verkauf pro Verkäufer im August
Wir wollen uns den maximalen Verkauf (in Stück) eines Computers pro Verkäufer im August anzeigen lassen.

#+BEGIN_SRC SQL
SELECT verkauf, max(qtj_2006_08)
FROM verkauf
GROUP BY verkaeufer
#+END_SRC

* Durchschnittliche Anzahl der Verkäufe pro Modell
